import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { delimiter, join } from "node:path";
import test from "node:test";

import {
  callConfiguredAiText,
  QuickCommitError,
  runQuickCommitWithFallback,
} from "../src/git-quick-commit.js";
import type { SessionProvider } from "../src/types.js";

function executable(path: string, body: string): void {
  writeFileSync(path, `#!/bin/sh\n${body}\n`, { mode: 0o755 });
}

function git(cwd: string, ...args: string[]): string {
  return execFileSync("git", args, {
    cwd,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  }).trim();
}

function initRepo(repo: string): void {
  mkdirSync(repo, { recursive: true });
  git(repo, "init", "-q");
  git(repo, "config", "user.email", "wand-test@example.test");
  git(repo, "config", "user.name", "Wand Test");
  writeFileSync(join(repo, "tracked.txt"), "before\n");
  git(repo, "add", "tracked.txt");
  git(repo, "commit", "-qm", "initial");
}

function lines(path: string): string[] {
  return readFileSync(path, "utf8").trim().split("\n");
}

test("one-shot CLI rejects an early stdin close instead of throwing an uncaught EPIPE", async () => {
  const root = mkdtempSync(join(tmpdir(), "wand-quick-commit-stdin-"));
  const bin = join(root, "bin");
  mkdirSync(bin);
  executable(join(bin, "codex"), "exit 0");
  const previousPath = process.env.PATH;
  process.env.PATH = `${bin}${delimiter}${previousPath ?? ""}`;
  try {
    await assert.rejects(
      callConfiguredAiText({ system: "", prompt: "input ".repeat(200_000) }, root, "English", { provider: "codex" }),
      (error: unknown) => error instanceof QuickCommitError && error.code === "CLAUDE_CLI_FAILED",
    );
  } finally {
    process.env.PATH = previousPath;
    rmSync(root, { recursive: true, force: true });
  }
});

test("one-shot commit text keeps Codex ephemeral and dispatches Grok/Qoder/Gemini without selecting Claude", async () => {
  const root = mkdtempSync(join(tmpdir(), "wand-quick-commit-ai-provider-"));
  const bin = join(root, "bin");
  const codexArgsFile = join(root, "codex-args");
  const grokArgsFile = join(root, "grok-args");
  const qoderArgsFile = join(root, "qoder-args");
  const geminiArgsFile = join(root, "gemini-args");
  const geminiPromptFile = join(root, "gemini-prompt");
  const claudeMarker = join(root, "claude-called");
  mkdirSync(bin);
  executable(join(bin, "codex"), [
    'printf \'%s\\n\' "$@" > "$WAND_CODEX_ARGS_FILE"',
    'printf \'%s\\n\' \'{"type":"item.completed","item":{"type":"agent_message","text":"fix: generated by codex"}}\'',
  ].join("\n"));
  executable(join(bin, "grok"), [
    'printf \'%s\\n\' "$@" > "$WAND_GROK_ARGS_FILE"',
    'printf \'%s\\n\' \'{"type":"text","data":"fix: generated by grok"}\'',
  ].join("\n"));
  executable(join(bin, "qodercli"), [
    'printf \'%s\\n\' "$@" > "$WAND_QODER_ARGS_FILE"',
    'printf \'%s\\n\' \'{"type":"result","subtype":"success","result":"fix: generated by qoder"}\'',
  ].join("\n"));
  // gemini 的 prompt 走 stdin（`-p ""` 只负责钉住 headless），所以 shim 必须读 stdin。
  executable(join(bin, "gemini"), [
    'printf \'%s\\n\' "$@" > "$WAND_GEMINI_ARGS_FILE"',
    'cat > "$WAND_GEMINI_PROMPT_FILE"',
    'printf \'%s\\n\' \'{"type":"message","role":"assistant","content":"fix: generated by gemini","delta":true}\'',
  ].join("\n"));
  executable(join(bin, "claude"), [
    ': > "$WAND_CLAUDE_MARKER"',
    "exit 99",
  ].join("\n"));

  const previous = {
    PATH: process.env.PATH,
    codexArgs: process.env.WAND_CODEX_ARGS_FILE,
    grokArgs: process.env.WAND_GROK_ARGS_FILE,
    qoderArgs: process.env.WAND_QODER_ARGS_FILE,
    geminiArgs: process.env.WAND_GEMINI_ARGS_FILE,
    geminiPrompt: process.env.WAND_GEMINI_PROMPT_FILE,
    claudeMarker: process.env.WAND_CLAUDE_MARKER,
  };
  process.env.PATH = `${bin}${delimiter}${previous.PATH ?? ""}`;
  process.env.WAND_CODEX_ARGS_FILE = codexArgsFile;
  process.env.WAND_GROK_ARGS_FILE = grokArgsFile;
  process.env.WAND_QODER_ARGS_FILE = qoderArgsFile;
  process.env.WAND_GEMINI_ARGS_FILE = geminiArgsFile;
  process.env.WAND_GEMINI_PROMPT_FILE = geminiPromptFile;
  process.env.WAND_CLAUDE_MARKER = claudeMarker;

  try {
    const codex = await callConfiguredAiText({ system: "", prompt: "codex prompt" }, root, "English", {
      provider: "codex",
      model: "codex-test-model",
      thinkingEffort: "codex:xhigh",
    });
    const grok = await callConfiguredAiText({ system: "grok rules", prompt: "grok prompt" }, root, "English", {
      provider: "grok",
      model: "grok-test-model",
      thinkingEffort: "max",
    });
    const qoder = await callConfiguredAiText({ system: "qoder rules", prompt: "qoder prompt" }, root, "English", {
      provider: "qoder",
      model: "qoder-test-model",
      thinkingEffort: "deep",
    });

    const gemini = await callConfiguredAiText({ system: "gemini rules", prompt: "gemini prompt" }, root, "English", {
      provider: "gemini",
      model: "gemini-test-model",
      thinkingEffort: "max",
    });

    assert.equal(codex, "fix: generated by codex");
    assert.equal(grok, "fix: generated by grok");
    assert.equal(qoder, "fix: generated by qoder");
    assert.equal(gemini, "fix: generated by gemini");
    assert.equal(existsSync(claudeMarker), false);

    const codexArgs = lines(codexArgsFile);
    assert.deepEqual(codexArgs.slice(0, 2), ["exec", "--ephemeral"]);
    assert.equal(codexArgs.includes("--json"), true);
    assert.deepEqual(codexArgs.slice(codexArgs.indexOf("--sandbox"), codexArgs.indexOf("--sandbox") + 2), [
      "--sandbox",
      "read-only",
    ]);
    assert.deepEqual(codexArgs.slice(codexArgs.indexOf("-c"), codexArgs.indexOf("-c") + 2), [
      "-c",
      "model_reasoning_effort=xhigh",
    ]);
    assert.equal(codexArgs.at(-1), "-");

    // gemini 没有 --append-system-prompt，规则并进 stdin 的 prompt；thinking 无开关。
    const geminiArgs = lines(geminiArgsFile);
    assert.deepEqual(geminiArgs, [
      "-p", "", "--output-format", "stream-json", "--skip-trust", "--model", "gemini-test-model",
    ]);
    const geminiPrompt = readFileSync(geminiPromptFile, "utf8");
    assert.match(geminiPrompt, /gemini rules/);
    assert.match(geminiPrompt, /gemini prompt/);

    const grokArgs = lines(grokArgsFile);
    assert.deepEqual(grokArgs.slice(0, 5), [
      "--no-auto-update",
      "-p",
      "grok prompt",
      "--output-format",
      "streaming-json",
    ]);
    assert.deepEqual(grokArgs.slice(grokArgs.indexOf("--model"), grokArgs.indexOf("--model") + 2), [
      "--model",
      "grok-test-model",
    ]);
    assert.deepEqual(grokArgs.slice(grokArgs.indexOf("--effort"), grokArgs.indexOf("--effort") + 2), [
      "--effort",
      "xhigh",
    ]);
    // 规则走 Grok 自己的系统提示开关（--rules），不做成“用户内容”。
    assert.deepEqual(grokArgs.slice(grokArgs.indexOf("--rules"), grokArgs.indexOf("--rules") + 2), [
      "--rules",
      "grok rules",
    ]);

    const qoderArgs = lines(qoderArgsFile);
    assert.deepEqual(qoderArgs.slice(0, 5), [
      "-p",
      "qoder prompt",
      "--output-format",
      "stream-json",
      "--no-session-persistence",
    ]);
    assert.deepEqual(qoderArgs.slice(qoderArgs.indexOf("--model"), qoderArgs.indexOf("--model") + 2), [
      "--model",
      "qoder-test-model",
    ]);
    assert.deepEqual(qoderArgs.slice(qoderArgs.indexOf("--reasoning-effort"), qoderArgs.indexOf("--reasoning-effort") + 2), [
      "--reasoning-effort",
      "high",
    ]);
    assert.deepEqual(qoderArgs.slice(qoderArgs.indexOf("--append-system-prompt"), qoderArgs.indexOf("--append-system-prompt") + 2), [
      "--append-system-prompt",
      "qoder rules",
    ]);
    // Codex 没有系统提示开关：规则只能并进内容（stdin），不能凭空多出参数。
    assert.equal(codexArgs.some((arg) => arg.includes("system")), false);
  } finally {
    if (previous.PATH === undefined) delete process.env.PATH;
    else process.env.PATH = previous.PATH;
    if (previous.codexArgs === undefined) delete process.env.WAND_CODEX_ARGS_FILE;
    else process.env.WAND_CODEX_ARGS_FILE = previous.codexArgs;
    if (previous.grokArgs === undefined) delete process.env.WAND_GROK_ARGS_FILE;
    else process.env.WAND_GROK_ARGS_FILE = previous.grokArgs;
    if (previous.qoderArgs === undefined) delete process.env.WAND_QODER_ARGS_FILE;
    else process.env.WAND_QODER_ARGS_FILE = previous.qoderArgs;
    if (previous.geminiArgs === undefined) delete process.env.WAND_GEMINI_ARGS_FILE;
    else process.env.WAND_GEMINI_ARGS_FILE = previous.geminiArgs;
    if (previous.geminiPrompt === undefined) delete process.env.WAND_GEMINI_PROMPT_FILE;
    else process.env.WAND_GEMINI_PROMPT_FILE = previous.geminiPrompt;
    if (previous.claudeMarker === undefined) delete process.env.WAND_CLAUDE_MARKER;
    else process.env.WAND_CLAUDE_MARKER = previous.claudeMarker;
    rmSync(root, { recursive: true, force: true });
  }
});

test("agentic quick-commit fallback dispatches Grok, Qoder, and Gemini with provider-native approval flags", async () => {
  const root = mkdtempSync(join(tmpdir(), "wand-quick-commit-ai-fallback-"));
  const bin = join(root, "bin");
  mkdirSync(bin);
  executable(join(bin, "grok"), [
    'printf \'%s\\n\' "$@" > "$WAND_PROVIDER_ARGS_FILE"',
    "git commit --no-verify -m 'grok fallback' >/dev/null",
    'printf \'%s\\n\' \'{"type":"text","data":"done"}\'',
  ].join("\n"));
  executable(join(bin, "qodercli"), [
    'printf \'%s\\n\' "$@" > "$WAND_PROVIDER_ARGS_FILE"',
    "git commit --no-verify -m 'qoder fallback' >/dev/null",
    'printf \'%s\\n\' \'{"type":"result","subtype":"success","result":"done"}\'',
  ].join("\n"));
  executable(join(bin, "gemini"), [
    'printf \'%s\\n\' "$@" > "$WAND_PROVIDER_ARGS_FILE"',
    "cat > /dev/null",
    "git commit --no-verify -m 'gemini fallback' >/dev/null",
    'printf \'%s\\n\' \'{"type":"message","role":"assistant","content":"done","delta":true}\'',
  ].join("\n"));

  const previousPath = process.env.PATH;
  const previousArgsFile = process.env.WAND_PROVIDER_ARGS_FILE;
  process.env.PATH = `${bin}${delimiter}${previousPath ?? ""}`;

  async function verifyProvider(
    provider: SessionProvider,
    expectedMessage: string,
    expectedApprovalFlag: string,
  ): Promise<void> {
    const repo = join(root, `repo-${provider}`);
    const argsFile = join(root, `${provider}-fallback-args`);
    initRepo(repo);
    writeFileSync(join(repo, "tracked.txt"), "after\n");
    writeFileSync(join(repo, ".git", "hooks", "pre-commit"), "#!/bin/sh\nexit 1\n", { mode: 0o755 });
    process.env.WAND_PROVIDER_ARGS_FILE = argsFile;

    const result = await runQuickCommitWithFallback({
      cwd: repo,
      language: "English",
      provider,
      model: `${provider}-test-model`,
      thinkingEffort: "max",
      autoMessage: false,
      customMessage: "built-in commit",
    });

    assert.equal(result.commit.message, expectedMessage);
    const args = lines(argsFile);
    assert.equal(args.includes(expectedApprovalFlag), true);
    assert.deepEqual(args.slice(args.indexOf("--model"), args.indexOf("--model") + 2), [
      "--model",
      `${provider}-test-model`,
    ]);
    if (provider === "qoder") {
      const effortIndex = args.indexOf("--reasoning-effort");
      assert.deepEqual(args.slice(effortIndex, effortIndex + 2), [
        "--reasoning-effort",
        "max",
      ]);
      const permissionIndex = args.indexOf("--permission-mode");
      assert.deepEqual(args.slice(permissionIndex, permissionIndex + 2), [
        "--permission-mode",
        "bypass_permissions",
      ]);
    }
  }

  try {
    await verifyProvider("grok", "grok fallback", "--always-approve");
    await verifyProvider("qoder", "qoder fallback", "--permission-mode");
    await verifyProvider("gemini", "gemini fallback", "--approval-mode");
  } finally {
    if (previousPath === undefined) delete process.env.PATH;
    else process.env.PATH = previousPath;
    if (previousArgsFile === undefined) delete process.env.WAND_PROVIDER_ARGS_FILE;
    else process.env.WAND_PROVIDER_ARGS_FILE = previousArgsFile;
    rmSync(root, { recursive: true, force: true });
  }
});

test("iteration digests replace the raw diff in generated commit messages", async () => {
  const root = mkdtempSync(join(tmpdir(), "wand-quick-commit-iteration-"));
  const bin = join(root, "bin");
  const promptFile = join(root, "codex-prompt");
  mkdirSync(bin);
  // codex 从 stdin 读 prompt：落盘后回一条固定 message，方便断言 prompt 里到底装了什么。
  executable(join(bin, "codex"), [
    'cat > "$WAND_PROMPT_FILE"',
    'printf \'%s\\n\' \'{"type":"item.completed","item":{"type":"agent_message","text":"fix: 按迭代提示词总结"}}\'',
  ].join("\n"));

  const previousPath = process.env.PATH;
  const previousPromptFile = process.env.WAND_PROMPT_FILE;
  process.env.PATH = `${bin}${delimiter}${previousPath ?? ""}`;
  process.env.WAND_PROMPT_FILE = promptFile;

  const digest = "1. 02-14 09:05 把登录页的错误提示改成中文\n2. 02-14 10:30 补一条空密码的测试";
  async function commitWith(options: { iterationDigest?: string; includeDiff?: boolean }): Promise<string> {
    const repo = join(root, `repo-${options.iterationDigest ? (options.includeDiff ? "diff" : "digest") : "legacy"}`);
    initRepo(repo);
    // 只在 diff 正文里出现的标记：用来确认「读没读代码」。
    writeFileSync(join(repo, "tracked.txt"), "DIFF_BODY_MARKER\n");
    const result = await runQuickCommitWithFallback({
      cwd: repo,
      language: "中文",
      provider: "codex",
      model: "codex-test-model",
      autoMessage: true,
      push: false,
      submodule: false,
      ...options,
    });
    assert.equal(result.ok, true);
    assert.equal(result.commit?.message, "fix: 按迭代提示词总结");
    return readFileSync(promptFile, "utf8");
  }

  try {
    // 默认（有迭代提示词）：只给提示词清单 + 文件清单，不读 diff 正文。
    const prompt = await commitWith({ iterationDigest: digest });
    assert.match(prompt, /把登录页的错误提示改成中文/);
    assert.match(prompt, /补一条空密码的测试/);
    assert.match(prompt, /tracked\.txt/, "文件清单要留着给模型核对");
    assert.doesNotMatch(prompt, /DIFF_BODY_MARKER/, "迭代模式不应该把完整 diff 灌给模型");

    // 显式要 diff：仍然带完整改动，用于提示词不够时逐行核对。
    const withDiff = await commitWith({ iterationDigest: digest, includeDiff: true });
    assert.match(withDiff, /把登录页的错误提示改成中文/);
    assert.match(withDiff, /DIFF_BODY_MARKER/);

    // 没有迭代提示词（老客户端 / 无记录）：保持旧行为，直接读 diff。
    const legacy = await commitWith({});
    assert.match(legacy, /DIFF_BODY_MARKER/);
    assert.doesNotMatch(legacy, /把登录页的错误提示改成中文/);
  } finally {
    if (previousPath === undefined) delete process.env.PATH;
    else process.env.PATH = previousPath;
    if (previousPromptFile === undefined) delete process.env.WAND_PROMPT_FILE;
    else process.env.WAND_PROMPT_FILE = previousPromptFile;
    rmSync(root, { recursive: true, force: true });
  }
});
