import type { Express, RequestHandler } from "express";
import { asyncRoute } from "./express-async.js";
import { getErrorMessage } from "./error-utils.js";
import type { WandStorage } from "./storage.js";
import type { SessionRegistry } from "./session-registry.js";
import type { WandTaskPriority, WandTaskStatus } from "./task-types.js";

const STATUSES = new Set<WandTaskStatus>(["todo", "doing", "done"]);
const PRIORITIES = new Set<WandTaskPriority>(["none", "low", "medium", "high", "urgent"]);
function dateValue(value: unknown): string | null | undefined { if (value === undefined) return undefined; if (value === null || value === "") return null; if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value.trim())) throw new Error("截止日期必须使用 YYYY-MM-DD 格式。"); return value.trim(); }
function bodyObject(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("请求体必须是对象。"); return value as Record<string, unknown>; }
function text(value: unknown): string { return typeof value === "string" ? value.trim() : ""; }
function taskDto(storage: WandStorage, task: ReturnType<WandStorage["getWandTask"]>) { if (!task) return null; return { ...task, sessionIds: storage.listWandTaskSessionIds(task.id) }; }

export function registerTaskRoutes(app: Express, storage: WandStorage, sessions?: SessionRegistry, requireAdmin?: RequestHandler): void {
  const guard = requireAdmin ?? ((_req, _res, next) => next());
  app.get("/api/wand-tasks", guard, (req, res) => res.json(storage.listWandTasks(typeof req.query.workspaceId === "string" ? req.query.workspaceId : undefined).map((task) => taskDto(storage, task))));
  app.post("/api/wand-tasks", guard, (req, res) => { try { const body = bodyObject(req.body); const title = text(body.title); if (!title) throw new Error("任务标题不能为空。"); const workspaceId = body.workspaceId === null ? null : text(body.workspaceId) || null; if (workspaceId && !storage.getWorkspace(workspaceId)) throw new Error("项目不存在。"); const status = STATUSES.has(body.status as WandTaskStatus) ? body.status as WandTaskStatus : "todo"; const priority = PRIORITIES.has(body.priority as WandTaskPriority) ? body.priority as WandTaskPriority : "none"; const labels = Array.isArray(body.labels) ? body.labels.filter((item): item is string => typeof item === "string").map((item) => item.trim()).filter(Boolean).slice(0, 20) : []; const task = storage.createWandTask({ workspaceId, title, description: text(body.description), status, priority, labels, dueDate: dateValue(body.dueDate) ?? null }); res.status(201).json(taskDto(storage, task)); } catch (error) { res.status(400).json({ error: getErrorMessage(error, "无法创建任务。") }); } });
  app.patch("/api/wand-tasks/:id", guard, (req, res) => { try { const body = bodyObject(req.body); const patch: Parameters<WandStorage["updateWandTask"]>[1] = {}; if (body.title !== undefined) { const value = text(body.title); if (!value) throw new Error("任务标题不能为空。"); patch.title = value; } if (body.description !== undefined) patch.description = text(body.description); if (body.status !== undefined) { if (!STATUSES.has(body.status as WandTaskStatus)) throw new Error("任务状态无效。"); patch.status = body.status as WandTaskStatus; } if (body.priority !== undefined) { if (!PRIORITIES.has(body.priority as WandTaskPriority)) throw new Error("任务优先级无效。"); patch.priority = body.priority as WandTaskPriority; } if (body.labels !== undefined) patch.labels = Array.isArray(body.labels) ? body.labels.filter((item): item is string => typeof item === "string").map((item) => item.trim()).filter(Boolean).slice(0, 20) : []; if (body.dueDate !== undefined) patch.dueDate = dateValue(body.dueDate) ?? null; if (body.workspaceId !== undefined) { const workspaceId = body.workspaceId === null ? null : text(body.workspaceId); if (workspaceId && !storage.getWorkspace(workspaceId)) throw new Error("项目不存在。"); patch.workspaceId = workspaceId || null; } if (body.sortOrder !== undefined && Number.isFinite(Number(body.sortOrder))) patch.sortOrder = Math.floor(Number(body.sortOrder)); const task = storage.updateWandTask(req.params.id, patch); if (!task) { res.status(404).json({ error: "未找到该任务。" }); return; } res.json(taskDto(storage, task)); } catch (error) { res.status(400).json({ error: getErrorMessage(error, "无法更新任务。") }); } });
  app.delete("/api/wand-tasks/:id", guard, (req, res) => { if (!storage.getWandTask(req.params.id)) { res.status(404).json({ error: "未找到该任务。" }); return; } storage.deleteWandTask(req.params.id); res.json({ ok: true }); });
  app.post("/api/wand-tasks/:id/sessions", guard, (req, res) => { try { const body = bodyObject(req.body); const sessionId = text(body.sessionId); if (!sessionId) throw new Error("缺少 sessionId。"); if (sessions && !sessions.get(sessionId)) throw new Error("未找到该会话。"); storage.bindWandTaskSession(req.params.id, sessionId); res.status(201).json(taskDto(storage, storage.getWandTask(req.params.id))); } catch (error) { res.status(400).json({ error: getErrorMessage(error, "无法绑定会话。") }); } });
  app.delete("/api/wand-tasks/:id/sessions/:sessionId", guard, (req, res) => { storage.unbindWandTaskSession(req.params.id, req.params.sessionId); res.json({ ok: true }); });
  app.get("/api/wand-tasks/:id", guard, asyncRoute(async (req, res) => { const task = taskDto(storage, storage.getWandTask(req.params.id)); if (!task) { res.status(404).json({ error: "未找到该任务。" }); return; } res.json(task); }));
}
