import type { ContentBlock, ToolResultBlock, ToolUseBlock } from "./types.js";

export const TOOL_PREVIEW_LIMIT = 180;

/** A small, literal excerpt for a collapsed card, never generated by a model. */
export function compactPreviewText(value: string): string {
  const text = value.slice(0, 8_192)
    .replace(/\x1b\[[0-9;]*[A-Za-z]/g, "")
    .replace(/(?:Bearer\s+)[\w.+/=-]+/gi, "Bearer [隐藏]")
    .replace(/((?:api[_-]?key|access[_-]?token|token|password|secret)\s*[=:]\s*)[^\s,;]+/gi, "$1[隐藏]")
    .replace(/\s+/g, " ").trim();
  return text.length > TOOL_PREVIEW_LIMIT ? text.slice(0, TOOL_PREVIEW_LIMIT - 1) + "…" : text;
}

function stringField(input: Record<string, unknown>, ...keys: string[]): string {
  for (const key of keys) {
    if (typeof input[key] === "string" && input[key].trim()) return input[key] as string;
  }
  return "";
}

function shortPath(path: string): string {
  return path.replace(/\\/g, "/").split("/").filter(Boolean).slice(-2).join("/");
}

function lineCount(text: string): number {
  return text ? text.split("\n").length - (text.endsWith("\n") ? 1 : 0) : 0;
}

export function toolInputPreview(use: Pick<ToolUseBlock, "name" | "input" | "description" | "preview">): string {
  if (use.preview) return compactPreviewText(use.preview);
  const input = use.input ?? {};
  const name = use.name.toLowerCase().split(/\/|__/).pop() ?? "";
  const path = shortPath(stringField(input, "file_path", "path", "filename", "file", "notebook_path"));
  const command = stringField(input, "command", "cmd", "script");
  let parts: string[] = [];
  if (command) {
    parts = [command];
  } else if (Array.isArray(input.tool_uses)) {
    const calls = input.tool_uses.filter((value): value is Record<string, unknown> => !!value && typeof value === "object");
    parts = [`并行 ${calls.length} 个工具`, calls.slice(0, 3).map(call => stringField(call, "recipient_name", "name")).filter(Boolean).join("、")];
  } else if (typeof input.code === "string") {
    const calls = [...new Set(Array.from(input.code.slice(0, 16_384).matchAll(/tools\.(\w+)\s*\(/g), match => match[1]))];
    parts = [calls.length ? `脚本调用 ${calls.slice(0, 4).join("、")}` : "执行代码", use.description || ""];
  } else if (Array.isArray(input.urls)) {
    const urls = input.urls.filter((value): value is string => typeof value === "string");
    parts = [`读取 ${urls.length} 个网址`, ...urls.slice(0, 2).map(value => {
      try { const url = new URL(value); return url.hostname + url.pathname; } catch { return "网址"; }
    })];
  } else if (/edit|write|replace|patch|file_change/.test(name)) {
    parts = [path];
    if (Array.isArray(input.edits)) parts.push(`${input.edits.length} 处替换`);
    else if (typeof input.old_string === "string" && typeof input.new_string === "string") {
      parts.push(`替换 ${lineCount(input.old_string)} 行 → ${lineCount(input.new_string)} 行`);
    } else if (typeof input.content === "string") parts.push(`写入 ${lineCount(input.content)} 行`);
    const patch = stringField(input, "patch", "unified_diff");
    if (patch) {
      const paths = Array.from(patch.matchAll(/^(?:\*\*\* (?:Update|Add|Delete) File: |\+\+\+ b\/)(.+)$/gm), match => shortPath(match[1]));
      if (paths.length) parts.push([...new Set(paths)].slice(0, 3).join("、"));
    }
  } else if (/grep|glob|search|find/.test(name)) {
    const query = stringField(input, "pattern", "query", "search", "regex");
    const queries = Array.isArray(input.queries) ? input.queries.filter((v): v is string => typeof v === "string") : [];
    parts = [query || queries.slice(0, 2).join("；"), path ? `范围 ${path}` : "", stringField(input, "glob", "include")];
  } else if (path) {
    parts = [path];
    const offset = input.offset ?? input.start_line;
    const limit = input.limit ?? input.end_line;
    if (typeof offset === "number") parts.push(`起始行 ${offset}`);
    if (typeof limit === "number") parts.push(`${input.end_line !== undefined ? "结束行" : "最多"} ${limit}${input.end_line !== undefined ? "" : " 行"}`);
  } else if (typeof input.url === "string") {
    try {
      const url = new URL(input.url);
      parts = [url.hostname + url.pathname];
    } catch { parts = [input.url]; }
  } else if (Array.isArray(input.todos)) {
    const todos = input.todos.filter((v): v is Record<string, unknown> => !!v && typeof v === "object");
    const done = todos.filter(todo => todo.status === "completed").length;
    const active = todos.find(todo => todo.status === "in_progress");
    parts = [`${done}/${todos.length} 项完成`, active ? stringField(active, "activeForm", "content", "subject") : ""];
  } else {
    parts = [stringField(input, "action", "agent"), stringField(input, "subject", "title", "description", "task", "prompt", "query", "name") || use.description || ""];
    if (!parts.some(Boolean)) {
      parts = Object.entries(input).filter(([key, value]) =>
        !/token|password|secret|key|content|body|data|code/i.test(key) && ["string", "number", "boolean"].includes(typeof value))
        .slice(0, 2).map(([key, value]) => `${key}: ${String(value)}`);
    }
  }
  return compactPreviewText(parts.filter(Boolean).join(" · "));
}

export function toolResultPreview(result: Pick<ToolResultBlock, "content" | "is_error" | "preview" | "_truncated">): string {
  if (result.preview) return compactPreviewText(result.preview);
  const raw = typeof result.content === "string" ? result.content : result.content
    .filter(part => part.type === "text" && typeof part.text === "string")
    .slice(0, 3).map(part => part.text as string).join("\n");
  if (!raw.trim()) return "";
  let text = raw;
  let exit = "";
  if (raw.length <= 65_536 && /^\s*[{[]/.test(raw)) {
    try {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed)) return `返回 ${parsed.length} 项`;
      if (parsed && typeof parsed === "object") {
        const code = parsed.exit_code ?? parsed.exitCode;
        if (typeof code === "number") exit = `退出码 ${code}`;
        text = stringField(parsed, "error", "message", "summary", "output", "stdout", "result");
        if (!text) {
          const rows = parsed.results ?? parsed.matches ?? parsed.items;
          if (Array.isArray(rows)) text = `返回 ${rows.length} 项`;
          else text = Object.entries(parsed).filter(([key, value]) =>
            /^(?:status|count|total|success|passed|failed|duration|wall_time_seconds)$/.test(key) &&
            ["string", "number", "boolean"].includes(typeof value)).map(([key, value]) => `${key}: ${value}`).join(" · ");
        }
      }
    } catch { /* Plain tool output may begin with a bracket. */ }
  }
  const sample = text.length > 8_192 ? text.slice(0, 2_048) + "\n…\n" + text.slice(-6_144) : text;
  const lines = sample.split(/\r?\n/).map(line => line.trim()).filter(Boolean);
  const facts = lines.filter(line => /(?:error|failed|failure|passed|\b(?:pass|fail|tests?)\b|exit(?:ed)?(?: code)?|BUILD (?:SUCCESS|FAIL)|错误|失败|通过|命中|找到)/i.test(line));
  const selected = (facts.length ? facts.slice(-2) : result.is_error ? lines.slice(-2) : lines.slice(0, 2)).join(" · ");
  return compactPreviewText([exit, selected].filter(Boolean).join(" · "));
}

/** Called at transport boundaries; provider history and full detail remain untouched. */
export function withToolPreview(block: ContentBlock): ContentBlock {
  if (block.type === "tool_use") {
    const preview = toolInputPreview(block);
    return preview ? { ...block, preview } : block;
  }
  if (block.type === "tool_result") {
    const preview = toolResultPreview(block);
    return preview ? { ...block, preview } : block;
  }
  return block;
}
